services:
  backend:
    build: ./backend
    working_dir: /backend/rimsnap
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    networks:
      - app-network
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    networks:
      - app-network
    depends_on:
      - backend
    command: bash -c "npm install && npm run dev"

networks:
  app-network:
    driver: bridge