services:
  backend:
    build: ./backend
    working_dir: /backend/rimsnap
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: bash -c "python rimsnap/manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: bash -c "npm install && npm run dev"